In [48]:
from data import X_train, y_train, X_test, y_test, columns
from sklearn.linear_model import LinearRegression

In [49]:
reg = LinearRegression().fit(X_train[:, 0].reshape(-1, 1), y_train)

In [50]:
reg.coef_

array([0.07857423])

In [51]:
reg.intercept_

13.54411694908767

In [52]:
y_pred = reg.predict(X_train[:, 0].reshape(-1, 1))
np.sum((y_pred - y_train) ** 2) / X_train.shape[0]

228.33110436124124

In [53]:
y_pred_test = reg.predict(X_test[:, 0].reshape(-1, 1))
np.sum((y_pred_test - y_test) ** 2) / X_test.shape[0]

81.13880035202945

In [24]:
reg2 = LinearRegression().fit(X_train, y_train)

In [25]:
reg2.coef_

array([ 0.11099299,  0.0948374 ,  0.08621412, -0.17566156,  0.31176713,
        0.01330098,  0.01045495,  0.11536365])

In [75]:
np.dot(reg2.coef_, X_train[2]) + reg2.intercept_

56.732863446851

In [76]:
y_train[2]

40.269535256000005

In [78]:
reg2.score(X_train, y_train)

0.612719983908171

In [26]:
reg2.intercept_

-3.3907376752996043

In [44]:
import numpy as np
y_pred = reg2.predict(X_train)
np.sum((y_pred - y_train) ** 2) / X_train.shape[0]

114.58251679829434

In [45]:
y_pred_test = reg2.predict(X_test)
np.sum((y_pred_test - y_test) ** 2) / X_test.shape[0]

60.5134110753203

In [47]:
y_pred

array([52.99846694, 53.19798163, 56.73286345, 67.69241057, 60.65707593,
       26.67808229, 68.45980095, 29.58224956, 19.52553574, 31.11703031,
       29.50888936, 22.35634281, 58.2676442 , 25.45025769, 20.13944804,
       28.51981919, 30.98076806, 59.63091173, 36.73479611, 48.65230571,
       47.88491534, 23.82822151, 20.94413016, 41.36349691, 60.24482403,
       49.2852769 , 57.50025382, 38.28863575, 30.34963993, 28.69439358,
       59.01699943, 58.40308713, 39.89161821, 59.03503457, 57.17526253,
       55.1980827 , 27.28007844, 35.96740573, 38.26957686, 44.81535384,
       27.90590689, 69.22719132, 66.15762983, 38.90254805, 37.50218648,
       27.9270032 , 24.32711004, 47.11752496, 24.8574417 , 27.15961283,
       46.35013459, 35.83298655, 34.43262498, 27.29199459, 21.40558478,
       19.93370608, 69.9945817 , 19.47225146, 37.67472345, 28.81485919,
       48.0574523 , 47.44354   , 19.4443904 , 46.21571541, 37.06081115,
       48.6713646 , 62.12895463, 26.39222245, 18.29771114, 51.28

In [1]:
sorted_models = [
    {'index': 'all', 'feature_name': 'all', 'mse_train': 118.58631233454756, 'mse_test': 62.10907801096792},
{'index': 1, 'feature_name': 'Cement (component 1)(kg in a m^3 mixture)', 'mse_train': 249.2751597663457, 'mse_test': 110.80916268760141, 'w_uni': 0.11974559950451338, 'w_multi': 0.11587731161580657},
{'index': 6, 'feature_name': 'Coarse Aggregate  (component 6)(kg in a m^3 mixture)', 'mse_train': 322.3370494098269, 'mse_test': 165.9516604247475, 'w_uni': 0.03658603454658212, 'w_multi': 0.0015553482483320331},
{'index': 7, 'feature_name': 'Fine Aggregate (component 7)(kg in a m^3 mixture)', 'mse_train': 333.4163390518505, 'mse_test': 171.51807109268617, 'w_uni': 0.04592066616867925, 'w_multi': 0.012000409221842579},
{'index': 4, 'feature_name': 'Water  (component 4)(kg in a m^3 mixture)', 'mse_train': 358.1442025850574, 'mse_test': 186.8708342127432, 'w_uni': 0.19494080882552947, 'w_multi': -0.1395968504946181},
{'index': 5, 'feature_name': 'Superplasticizer (component 5)(kg in a m^3 mixture)', 'mse_train': 741.6108332870022, 'mse_test': 303.4062929129108, 'w_uni': 2.6914598982103772, 'w_multi': 0.03720445280296879},
{'index': 8, 'feature_name': 'Age (day)', 'mse_train': 931.4604030061139, 'mse_test': 666.1896684701678, 'w_uni': 0.30999871286414055, 'w_multi': 0.1073265577047291},
{'index': 2, 'feature_name': 'Blast Furnace Slag (component 2)(kg in a m^3 mixture)', 'mse_train': 1002.9135327137514, 'mse_test': 343.5963796620217, 'w_uni': 0.22047899251681402, 'w_multi': 0.09706403050947152},
{'index': 3, 'feature_name': 'Fly Ash (component 3)(kg in a m^3 mixture)', 'mse_train': 1115.1335178327136, 'mse_test': 750.1729157119987, 'w_uni': 0.27497533723772827, 'w_multi': 0.10392258030490145},
]

In [4]:
import csv

with open('result_summary.csv', 'w') as f:  # You will need 'wb' mode in Python 2.x
    w = csv.DictWriter(f, sorted_models[1].keys())
    w.writeheader()
    for model in sorted_models:
        w.writerow(model)

In [68]:
coef = [1.15877312e-01,  9.70640305e-02,  1.03922580e-01, -1.39596850e-01,  3.72044528e-02,  1.55534825e-03,  1.20004092e-02, 1.07326558e-01]
coef_norm = coef / np.mean(X_train, axis=0) * 10000

In [69]:

coef_norm[1]

14.170402657347081

In [5]:
extra_credit = [
    {'model': 'Multi Variate', 'mse_train': 118.58631233454756, 'mse_test': 62.10907801096792},
    {'model': 'Closed Form Solution', 'mse_train': 114.58251679829434, 'mse_test': 60.513411075338134},
    {'model': 'Polynomial Regression', 'mse_train': 191.37187045676671, 'mse_test': 95.1396623698323},
    {'model': 'Sparse Regression', 'mse_train': 170.61919983227614, 'mse_test': 59.80750263012047},
]
with open('extra_credit.csv', 'w') as f:  # You will need 'wb' mode in Python 2.x
    w = csv.DictWriter(f, extra_credit[1].keys())
    w.writeheader()
    for model in extra_credit:
        w.writerow(model)